### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Rexagon** [cliffrowley/atom-open-in-github-app#10]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Unknown Windows Version
**Thrown From**: [open-in-github-app](https://github.com/cliffrowley/atom-open-in-github-app) package, v0.2.4

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\Иван\.atom\packages\open-in-github-app\lib\open-in-github-app.coffee:9

TypeError: undefined is not a function
    at Object.module.exports.openApp (C:\Users\Иван\.atom\packages\open-in-github-app\lib\open-in-github-app.coffee:18:56)
    at atom-workspace.<anonymous> (C:\Users\Иван\.atom\packages\open-in-github-app\lib\open-in-github-app.coffee:12:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Иван\AppData\Local\atom\app-0.207.0\resources\app.asar\src\command-registry.js:238:29)
    at C:\Users\Иван\AppData\Local\atom\app-0.207.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Иван\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Иван\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Иван\AppData\Local\atom\app-0.207.0\resources\app.asar\src\window-event-handler.js:177:20)
```

### Commands

```
     -0:03.0 open-in-github-app:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
emmet, v2.3.10
open-in-github-app, v0.2.4

# Dev
No dev packages
```

**Comment by cliffrowley** [comment]
Excellent, thanks - I will get this sorted as soon as possible.  Windows support was requested by someone else and a pull request integrated but I don't have a way to test it right now (am on Mac only).  I'll post again when I've updated it, if you could let me know whether it works for you - and I'll make some effort to get a Windows VM together to test going forward.

**Comment by Raynes** [comment]
This is not a Windows issue. I'm seeing it on OS X.

**Comment by jugglingnutcase** [comment]
I'm pretty sure it's due to our use of deprecated APIs which were removed in recent versions. Hopefully this will all be fixed soon with the multiple-projects branch.

**Comment by cliffrowley** [comment]
Yep, we just need to resolve our conversation in the other thread and we (should be) ready to go :-)

**Comment by cliffrowley** [comment]
Fixed by https://github.com/cliffrowley/atom-open-in-github-app/pull/12
