### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by gbdu** [cliffrowley/atom-open-in-github-app#13]
[Enter steps to reproduce below:]

1. just installed atom-open-in-github-app and pressed ctrl-alt-g...
2. ...

**Atom Version**: 1.0.11
**System**: Linux Mint
**Thrown From**: [open-in-github-app](https://github.com/cliffrowley/atom-open-in-github-app) package, v0.2.6

### Stack Trace

Uncaught TypeError: object is not a function

```
At /home/gargantua/.atom/packages/open-in-github-app/lib/open-in-github-app.coffee:23

TypeError: object is not a function
  at Object.module.exports.openApp (/home/gargantua/.atom/packages/open-in-github-app/lib/open-in-github-app.coffee:23:7)
  at atom-workspace.<anonymous> (/home/gargantua/.atom/packages/open-in-github-app/lib/open-in-github-app.coffee:10:91)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -2:16.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  5x -2:13.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:12.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -2:12.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:12.1.0 settings-view:view-installed-themes (atom-text-editor.editor)
  3x -1:59.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:26 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:13 pane:show-next-item (atom-text-editor.editor.mini.is-focused)
     -1:10.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:43 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -0:41.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:39.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:39.1.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -0:35.7.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:32.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 open-in-github-app:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-modules, v1.1.0
autocomplete-python, v0.5.3
color-picker, v2.0.11
gtk-dark-theme, v0.1.4
open-in-github-app, v0.2.6
project-manager, v2.4.0
seti-icons, v0.4.5
seti-ui, v0.8.0
smart-tab-name, v1.0.3
terminal-status, v1.6.8

# Dev
No dev packages
```

**Comment by jugglingnutcase** [comment]
Thanks for sending in the bug report.

> System: Linux Mint

Looks like you're on a Linux machine, and GitHub doesn't have a linux application, so this package hasn't catered to Linux users much. Do you know what behavior you'd like to happen for this package when you launch the package?

**Comment by gbdu** [comment]
Opening the project in firefox would be cool

**Comment by cliffrowley** [comment]
There's already an 'Open on Github' package for that - I recommend we just show a dialog to explain that it's not supported on Linux due to a lack of Github client for Linux, rather than introduce behaviour which isn't specific to opening the project in the Github app :-)

**Comment by gbdu** [comment]
Thanks guys

**Comment by jugglingnutcase** [comment]
> rather than introduce behaviour which isn't specific to opening the project in the Github app

i think that's great input. thanks.
