### ISSUE TITLE
Uncaught TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by mayank1101** [cliffrowley/atom-open-in-github-app#15]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [open-in-github-app](https://github.com/cliffrowley/atom-open-in-github-app) package, v0.2.6

### Stack Trace

Uncaught TypeError: require(...) is not a function

```
At /home/mayank/.atom/packages/open-in-github-app/lib/open-in-github-app.coffee:23

TypeError: require(...) is not a function
    at Object.openApp (/home/mayank/.atom/packages/open-in-github-app/lib/open-in-github-app.coffee:23:7)
    at atom-workspace.<anonymous> (/home/mayank/.atom/packages/open-in-github-app/lib/open-in-github-app.coffee:10:91)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/opt/atom/resources/app.asar/src/atom-environment.js:1142:28)
    at EventEmitter.outerCallback (/opt/atom/resources/app.asar/src/application-delegate.js:332:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:25.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:24.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:23.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:22.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:16 tree-view:show-in-file-manager (span.name.icon.icon-file-directory)
     -0:00.2.0 open-in-github-app:open (span.name.icon.icon-file-directory)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.14 (active)
atom-django, v0.3.2 (active)
atom-javascript-console-snippets, v0.10.0 (active)
atom-live-server, v1.2.5 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.8 (inactive)
atom-python-run, v0.6.2 (active)
autocomplete-python, v1.8.20 (active)
data-atom, v0.24.0 (active)
format-sql, v0.3.0 (inactive)
github-plus, v1.0.0 (inactive)
javascript-snippets, v1.2.1 (active)
language-javascript-jsx, v0.3.7 (active)
language-javascript-semantic, v0.2.1 (active)
language-pgsql, v0.2.3 (active)
language-sql-mysql, v0.3.1 (active)
my-github-profile, v0.2.1 (active)
open-in-github-app, v0.2.6 (inactive)
php-cs-fixer, v4.0.0 (active)
php-integrator-autocomplete-plus, v1.2.0 (active)
php-integrator-base, v2.0.2 (active)
php-integrator-core, v2.0.2 (active)
php-integrator-linter, v1.3.0 (active)
php-server, v0.7.0 (inactive)
python-indent, v1.0.0 (active)
python-tools, v0.6.8 (active)
qolor, v0.4.1 (active)
quick-query, v0.8.8 (inactive)
run, v0.0.1 (active)
script, v3.13.0 (inactive)
server-script, v0.1.3 (active)
serverspec-snippets, v0.1.1 (active)
turbo-javascript, v1.4.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (active)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by jugglingnutcase** [comment]
Thanks for the bug report. Similar to the#13, the GitHub app isn't on Linux, so we can about improving the package to indicate that isn't useful for Atom on Linux.
